### ISSUE TITLE
Local Installation issues?

### ISSUE THREAD

**Issue by IdahoScott** [ginolhac/mapDamage#29]
Hi,

When trying to install mapDamage using the setup.py script on a remote machine (python setup.py --user), I receive this issue:

```
Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    "mapdamage.seqtk", sources=["mapdamage/seqtk/seqtk.c"], libraries=["z"],
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_py')
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/apps/intel18/python2/2.7.15/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 24, in run
    super().run()
TypeError: super() takes at least 1 argument (0 given)
```

Do you have any suggestions on the installation of this?

Thanks!

**Comment by MikkelSchubert** [comment]
mapDamage no longer supports python2, so you will need to use python3 instead:

    python3 setup.py --user

But thank you for the report. I've added a human-readable error message in case anyone else runs into this.
